# Generated by Django 5.0 on 2025-07-13 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0002_creneau_heure_debut_creneau_heure_fin_creneau_jour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Exemple: 2024-2025', max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
            },
        ),
        migrations.AddField(
            model_name='eleve',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professeur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='indemnisation',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Indemnisation mensuelle', max_digits=10),
        ),
        migrations.AddField(
            model_name='professeur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='professeur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classe',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='ecole_app.anneescolaire'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='ecole_app.anneescolaire'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='ecole_app.anneescolaire'),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('loyer', 'Loyer'), ('electricite', 'Électricité'), ('eau', 'Eau'), ('internet', 'Internet'), ('fournitures', 'Fournitures'), ('indemnisation', 'Indemnisation professeur'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='ecole_app.anneescolaire')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indemnisations', to='ecole_app.professeur')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
            },
        ),
        migrations.CreateModel(
            name='PresenceEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('justifie', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_eleves', to='ecole_app.classe')),
                ('creneau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_eleves', to='ecole_app.creneau')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='ecole_app.eleve')),
            ],
            options={
                'verbose_name': 'Présence élève',
                'verbose_name_plural': 'Présences élèves',
                'unique_together': {('eleve', 'date', 'creneau')},
            },
        ),
        migrations.CreateModel(
            name='PresenceProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('justifie', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('creneau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_professeurs', to='ecole_app.creneau')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='ecole_app.professeur')),
            ],
            options={
                'verbose_name': 'Présence professeur',
                'verbose_name_plural': 'Présences professeurs',
                'unique_together': {('professeur', 'date', 'creneau')},
            },
        ),
    ]
