# Generated by Django 5.0 on 2025-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0003_anneescolaire_eleve_user_professeur_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text="Montant total à payer pour l'inscription", max_digits=10),
        ),
    ]
