# Generated by Django 5.0 on 2025-07-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0004_eleve_montant_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='mot_de_passe_en_clair',
            field=models.CharField(blank=True, help_text='Mot de passe en clair (non sécurisé)', max_length=100, null=True),
        ),
    ]
