# Generated by Django 5.0 on 2025-07-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0005_eleve_mot_de_passe_en_clair'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='remarque',
            field=models.TextField(blank=True, help_text="Remarque libre sur l'élève", null=True),
        ),
    ]
