# Generated by Django 5.0 on 2025-07-16 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0006_eleve_remarque'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnetPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carnet_pedagogique', to='ecole_app.eleve')),
            ],
            options={
                'verbose_name': 'Carnet pédagogique',
                'verbose_name_plural': 'Carnets pédagogiques',
            },
        ),
        migrations.CreateModel(
            name='EcouteAvantMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('debut_page', models.PositiveIntegerField()),
                ('fin_page', models.PositiveIntegerField()),
                ('remarques', models.TextField(blank=True)),
                ('carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecoutes', to='ecole_app.carnetpedagogique')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecoutes_supervisees', to='ecole_app.professeur')),
            ],
            options={
                'verbose_name': 'Écoute avant mémorisation',
                'verbose_name_plural': 'Écoutes avant mémorisation',
            },
        ),
        migrations.CreateModel(
            name='Memorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('debut_page', models.PositiveIntegerField()),
                ('fin_page', models.PositiveIntegerField()),
                ('remarques', models.TextField(blank=True)),
                ('carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorisations', to='ecole_app.carnetpedagogique')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorisations_supervisees', to='ecole_app.professeur')),
            ],
            options={
                'verbose_name': 'Mémorisation',
                'verbose_name_plural': 'Mémorisations',
            },
        ),
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourate', models.CharField(max_length=100)),
                ('page', models.PositiveIntegerField()),
                ('nombre_repetitions', models.PositiveIntegerField(default=0)),
                ('derniere_date', models.DateField(auto_now=True)),
                ('carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetitions', to='ecole_app.carnetpedagogique')),
            ],
            options={
                'verbose_name': 'Répétition',
                'verbose_name_plural': 'Répétitions',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.PositiveIntegerField(help_text="Numéro de la semaine dans l'année")),
                ('date', models.DateField()),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('nombre_hizb', models.PositiveIntegerField(default=0, help_text='Nombre de Hizb révisés')),
                ('carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ecole_app.carnetpedagogique')),
            ],
            options={
                'verbose_name': 'Révision',
                'verbose_name_plural': 'Révisions',
            },
        ),
    ]
