# Generated by Django 5.0 on 2025-07-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0007_carnetpedagogique_ecouteavantmemo_memorisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='nombre_hizb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nombre de Hizb révisés (décimal autorisé)', max_digits=4),
        ),
    ]
