# Generated by Django 5.0 on 2025-07-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0008_alter_revision_nombre_hizb'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='archive',
            field=models.BooleanField(default=False, help_text='Élève archivé'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='motif_archive',
            field=models.TextField(blank=True, help_text="Motif d'archivage", null=True),
        ),
    ]
