# Generated by Django 5.0 on 2025-07-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0009_eleve_archive_eleve_motif_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeAttente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('remarque', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_definitivement', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "Enfant en liste d'attente",
                'verbose_name_plural': "Liste d'attente",
            },
        ),
    ]
