# Generated by Django 5.0 on 2025-07-21 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0011_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la composante (ex: École Enfants, École Adultes, etc.)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la composante')),
                ('active', models.BooleanField(default=True, help_text='Composante active ou non')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Composante',
                'verbose_name_plural': 'Composantes',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annees_scolaires', to='ecole_app.composante'),
        ),
        migrations.AddField(
            model_name='carnetpedagogique',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carnets_pedagogiques', to='ecole_app.composante'),
        ),
        migrations.AddField(
            model_name='charge',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='ecole_app.composante'),
        ),
        migrations.AddField(
            model_name='classe',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ecole_app.composante'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='ecole_app.composante'),
        ),
        migrations.AddField(
            model_name='listeattente',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liste_attente', to='ecole_app.composante'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ecole_app.composante'),
        ),
        migrations.AddField(
            model_name='presenceeleve',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences_eleves', to='ecole_app.composante'),
        ),
        migrations.AddField(
            model_name='presenceprofesseur',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences_professeurs', to='ecole_app.composante'),
        ),
        migrations.AddField(
            model_name='professeur',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professeurs', to='ecole_app.composante'),
        ),
    ]
