# Generated by Django 5.0 on 2025-07-21 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0012_composante_anneescolaire_composante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='ecole_app.composante'),
        ),
    ]
