# Generated by Django 5.0 on 2025-08-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0013_creneau_composante'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archivé (non proposé dans les formulaires)'),
        ),
    ]
