# Generated by Django 5.0 on 2025-08-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0014_creneau_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='creneau',
        ),
        migrations.AddField(
            model_name='professeur',
            name='creneaux',
            field=models.ManyToManyField(blank=True, related_name='professeurs', to='ecole_app.creneau'),
        ),
    ]
