# Generated by Django 5.0 on 2025-08-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0015_remove_professeur_creneau_professeur_creneaux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='creneau',
        ),
        migrations.AddField(
            model_name='eleve',
            name='creneaux',
            field=models.ManyToManyField(blank=True, related_name='eleves', to='ecole_app.creneau'),
        ),
    ]
