# Generated by Django 5.0 on 2025-08-07 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0016_remove_eleve_creneau_eleve_creneaux'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='key',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='value',
        ),
        migrations.CreateModel(
            name='PaiementHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('methode', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='ecole_app.paiement')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configurations du site',
            },
        ),
    ]
