# Generated by Django 5.0 on 2025-08-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0017_alter_siteconfig_options_remove_siteconfig_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Configuration du site', 'verbose_name_plural': 'Configurations du site'},
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='key',
            field=models.CharField(default='default', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='value',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
