# Generated by Django 5.0 on 2025-08-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0018_alter_siteconfig_options_siteconfig_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='creneaux',
        ),
    ]
