# Generated by Django 5.0 on 2025-08-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0019_remove_professeur_creneaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='mot_de_passe_en_clair',
            field=models.CharField(blank=True, help_text='Mot de passe en clair (non sécurisé)', max_length=100, null=True),
        ),
    ]
