# Generated by Django 5.0 on 2025-08-07 21:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0020_professeur_mot_de_passe_en_clair'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('debutant', "Débutant (apprentissage de l'alphabet et lecture)"), ('intermediaire', 'Intermédiaire (lecture avec tajwid)'), ('avance', 'Avancé (révision, hifdh, perfectionnement)')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Niveau d'élève",
                'verbose_name_plural': "Niveaux d'élèves",
            },
        ),
        migrations.CreateModel(
            name='InscriptionEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, help_text="Laisser vide si l'inscription est toujours active", null=True)),
                ('active', models.BooleanField(default=True, help_text='Indique si cette inscription est active')),
                ('ancien_niveau', models.CharField(blank=True, help_text='Niveau précédent en cas de transfert', max_length=50, null=True)),
                ('raison_changement', models.TextField(blank=True, help_text='Raison du changement de niveau/classe')),
                ('date_changement', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_eleves', to='ecole_app.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_eleves', to='ecole_app.classe')),
                ('creneau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_eleves', to='ecole_app.creneau')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='ecole_app.eleve')),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='ecole_app.niveaueleve')),
            ],
            options={
                'verbose_name': 'Inscription élève',
                'verbose_name_plural': 'Inscriptions élèves',
                'unique_together': {('eleve', 'creneau', 'annee_scolaire', 'active')},
            },
        ),
        migrations.CreateModel(
            name='TarifInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_heures', models.PositiveIntegerField(help_text="Nombre d'heures par semaine")),
                ('montant_annuel', models.DecimalField(decimal_places=2, help_text='Montant annuel en euros', max_digits=10)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='ecole_app.anneescolaire')),
            ],
            options={
                'verbose_name': "Tarif d'inscription",
                'verbose_name_plural': "Tarifs d'inscription",
                'unique_together': {('nombre_heures', 'annee_scolaire')},
            },
        ),
    ]
