# Generated by Django 5.0 on 2025-08-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0021_niveaueleve_inscriptioneleve_tarifinscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarifinscription',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tarifinscription',
            name='annee_scolaire',
        ),
        migrations.AddField(
            model_name='eleve',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='eleves_multi', to='ecole_app.classe'),
        ),
        migrations.DeleteModel(
            name='InscriptionEleve',
        ),
        migrations.DeleteModel(
            name='NiveauEleve',
        ),
        migrations.DeleteModel(
            name='TarifInscription',
        ),
    ]
