# Generated by Django 5.0 on 2025-08-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0022_alter_tarifinscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiementhistorique',
            options={'verbose_name': 'Historique de paiement', 'verbose_name_plural': 'Historiques de paiements'},
        ),
        migrations.RemoveField(
            model_name='paiementhistorique',
            name='key',
        ),
        migrations.RemoveField(
            model_name='paiementhistorique',
            name='value',
        ),
        migrations.CreateModel(
            name='ObjectifMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text="Mois et année de l'objectif")),
                ('sourate', models.CharField(blank=True, help_text='Sourate ciblée', max_length=100, null=True)),
                ('numero_exercice', models.PositiveIntegerField(blank=True, help_text="Numéro d'exercice (1-13)", null=True)),
                ('description_libre', models.TextField(blank=True, help_text="Description libre de l'objectif")),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('atteint', 'Atteint'), ('non_atteint', 'Non atteint')], default='en_cours', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commentaire', models.TextField(blank=True, help_text="Commentaires sur l'objectif")),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='ecole_app.eleve')),
            ],
            options={
                'verbose_name': 'Objectif mensuel',
                'verbose_name_plural': 'Objectifs mensuels',
                'ordering': ['-mois', 'eleve'],
            },
        ),
    ]
