# Generated by Django 5.0 on 2025-08-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0023_alter_paiementhistorique_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectifmensuel',
            name='description_libre',
            field=models.TextField(blank=True, help_text="Description libre de l'objectif", null=True),
        ),
    ]
