# Generated by Django 5.0 on 2025-08-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0025_question_courspartage_module_document_choix_quiz_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presenceeleve',
            unique_together={('eleve', 'date', 'classe')},
        ),
    ]
