# Generated by Django 5.0 on 2025-08-09 14:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0026_alter_presenceeleve_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecon', models.IntegerField(choices=[(1, 'Leçon 1'), (2, 'Leçon 2'), (3, 'Leçon 3'), (4, 'Leçon 4'), (5, 'Leçon 5')], help_text='Numéro de la leçon')),
                ('description', models.TextField(help_text='Description de la compétence')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage de la compétence")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compétence du livre',
                'verbose_name_plural': 'Compétences du livre',
                'ordering': ['lecon', 'ordre'],
            },
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='EvaluationCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('acquis', 'Acquis'), ('non_acquis', 'Non Acquis'), ('en_cours', 'En cours')], default='en_cours', max_length=20)),
                ('date_evaluation', models.DateField(default=datetime.date.today)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='ecole_app.competencelivre')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_competences', to='ecole_app.eleve')),
            ],
            options={
                'verbose_name': 'Évaluation de compétence',
                'verbose_name_plural': 'Évaluations de compétences',
                'ordering': ['eleve', 'competence__lecon', 'competence__ordre'],
                'unique_together': {('eleve', 'competence')},
            },
        ),
    ]
