# Generated by Django 5.0 on 2025-08-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0027_competencelivre_alter_siteconfig_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='composante',
        ),
        migrations.AddField(
            model_name='professeur',
            name='composantes',
            field=models.ManyToManyField(blank=True, help_text='Composantes où enseigne ce professeur', related_name='professeurs', to='ecole_app.composante'),
        ),
    ]
