# Generated by Django 5.0 on 2025-08-10 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0028_professeur_multi_composantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='composantes',
        ),
        migrations.AddField(
            model_name='professeur',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professeurs', to='ecole_app.composante'),
        ),
    ]
