# Generated by Django 5.0 on 2025-08-10 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0029_rename_composante_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='composantes',
            field=models.ManyToManyField(blank=True, help_text='Composantes où enseigne ce professeur', related_name='professeurs', to='ecole_app.composante'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='composante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professeurs_old', to='ecole_app.composante'),
        ),
    ]
