# Generated by Django 5.0 on 2025-08-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0033_alter_competencelivre_lecon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencelivre',
            name='lecon',
            field=models.IntegerField(choices=[(1, 'Leçon 1'), (2, 'Leçon 2'), (3, 'Leçon 3'), (4, 'Leçon 4'), (5, 'Leçon 5'), (6, 'Leçon 6'), (7, 'Leçon 7'), (8, 'Leçon 8')], help_text='Numéro de la leçon'),
        ),
    ]
