# Generated by Django 5.0 on 2025-08-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0033_fix_professeur_composantes'),
        ('ecole_app', '0035_alter_competencelivre_lecon'),
    ]

    operations = [
    ]
