# Generated by Django 5.0 on 2025-08-10 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0036_merge_20250810_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre de l'examen (ex: Examen Sourate Al-Fatiha)", max_length=200)),
                ('type_examen', models.CharField(choices=[('recitation', 'Récitation'), ('ecriture', 'Écriture'), ('tajwid', 'Tajwid'), ('comprehension', 'Compréhension'), ('autre', 'Autre')], default='recitation', max_length=20)),
                ('sourate_concernee', models.CharField(blank=True, help_text="Sourate concernée par l'examen", max_length=100, null=True)),
                ('note', models.DecimalField(decimal_places=2, help_text='Note sur 20', max_digits=4)),
                ('note_max', models.DecimalField(decimal_places=2, default=20, help_text='Note maximale', max_digits=4)),
                ('date_examen', models.DateField(help_text="Date de l'examen")),
                ('commentaire', models.TextField(blank=True, help_text='Commentaires du professeur')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_examens', to='ecole_app.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_examens', to='ecole_app.eleve')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_donnees', to='ecole_app.professeur')),
            ],
            options={
                'verbose_name': "Note d'examen",
                'verbose_name_plural': "Notes d'examen",
                'ordering': ['-date_examen', '-date_creation'],
            },
        ),
    ]
