# Generated by Django 5.0 on 2025-08-21 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0037_noteexamen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='ecole_app.professeur'),
        ),
    ]
