# Generated by Django 5.0 on 2025-08-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0038_alter_module_professeur'),
    ]

    operations = [
    ]
