# Generated by Django 5.0 on 2025-08-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0039_merge_20250821_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_defaut_eleve', models.DecimalField(decimal_places=2, default=200.0, help_text='Montant par défaut pour les nouveaux élèves en euros', max_digits=10)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.AddField(
            model_name='objectifmensuel',
            name='page_debut',
            field=models.PositiveIntegerField(blank=True, help_text='Page de début de la sourate', null=True),
        ),
        migrations.AddField(
            model_name='objectifmensuel',
            name='page_fin',
            field=models.PositiveIntegerField(blank=True, help_text='Page de fin de la sourate', null=True),
        ),
        migrations.AlterField(
            model_name='noteexamen',
            name='type_examen',
            field=models.CharField(choices=[('recitation', 'Récitation'), ('ecriture', 'Écriture'), ('tajwid', 'Tajwid'), ('comprehension', 'Compréhension'), ('quiz', 'Quiz en ligne'), ('autre', 'Autre')], default='recitation', max_length=20),
        ),
        migrations.CreateModel(
            name='ProgressionCoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourate_actuelle', models.CharField(blank=True, help_text='Sourate actuellement en cours de mémorisation', max_length=100, null=True)),
                ('page_actuelle', models.PositiveIntegerField(default=1, help_text='Dernière page mémorisée')),
                ('direction_memorisation', models.CharField(choices=[('debut', 'Du début (Al-Baqara)'), ('fin', 'De la fin (An-Nas)')], default='debut', help_text='Direction de mémorisation (du début ou de la fin du Coran)', max_length=10)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression_coran', to='ecole_app.eleve')),
            ],
            options={
                'verbose_name': 'Progression du Coran',
                'verbose_name_plural': 'Progressions du Coran',
            },
        ),
    ]
