# Generated by Django 5.0 on 2025-08-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0040_parametresite_eleve_prenom_mere_eleve_prenom_pere_and_more'),
        ('ecole_app', '0041_progressioncoran'),
    ]

    operations = [
    ]
