# Generated by Django 5.0 on 2025-08-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0042_merge_20250822_1353'),
    ]

    operations = [
    ]
