# Generated by Django 5.0 on 2025-08-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0043_fix_parametresite_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='prenom_mere',
            field=models.CharField(blank=True, help_text='Prénom de la mère', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='prenom_pere',
            field=models.CharField(blank=True, help_text='Prénom du père', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='telephone_secondaire',
            field=models.CharField(blank=True, help_text='Numéro de téléphone secondaire', max_length=20, null=True),
        ),
    ]
