# Generated by Django 5.0 on 2025-08-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0043_create_parametresite'),
        ('ecole_app', '0043_fix_parametresite_and_conflicts'),
        ('ecole_app', '0044_fix_parametresite_table'),
    ]

    operations = [
    ]
