# Generated by Django 5.0 on 2025-08-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0046_add_page_debut_sourate'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressioncoran',
            name='page_debut_sourate',
            field=models.PositiveIntegerField(default=1, help_text='Page de début de la sourate actuelle'),
        ),
    ]
