# Generated by Django 5.0 on 2025-08-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0047_add_page_debut_sourate_progressioncoran'),
    ]

    operations = [
    ]
