# Generated by Django 5.0 on 2025-08-22 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0048_add_page_debut_sourate_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenceprofesseur',
            name='creneau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_professeurs', to='ecole_app.creneau'),
        ),
    ]
