# Generated by Django 5.0 on 2025-08-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole_app', '0040_add_creneau_to_presenceprofesseur'),
        ('ecole_app', '0049_alter_presenceprofesseur_creneau'),
        ('ecole_app', 'add_remarques_field'),
        ('ecole_app', 'add_remarques_to_revision'),
    ]

    operations = [
    ]
